//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANG_VON
    {
        public Nullable<System.Guid> KEY_NHAP_XUAT { get; set; }
        public System.Guid KEY_BANG_VON { get; set; }
        public Nullable<System.Guid> KEY_KHACH_HANG { get; set; }
        public Nullable<System.Guid> KEY_GIAO_DICH { get; set; }
        public Nullable<System.Guid> KEY_THANH_TOAN { get; set; }
        public Nullable<System.Guid> KEY_KHOAN_MUC { get; set; }
        public Nullable<decimal> TIEN_VIET_NAM { get; set; }
        public string GHI_DIEN_GIAI { get; set; }
    
        public virtual GIAO_DICH GIAO_DICH { get; set; }
        public virtual GIAO_DICH GIAO_DICH1 { get; set; }
        public virtual KHOAN_MUC KHOAN_MUC { get; set; }
        public virtual NHAP_XUAT NHAP_XUAT { get; set; }
    }
}
