//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_MEAL
    {
        public Nullable<short> INDEX_SAP_XEP { get; set; }
        public Nullable<System.Guid> KEY_HOA_DON { get; set; }
        public System.Guid KEY_BILL_MEAL { get; set; }
        public Nullable<System.Guid> KEY_MON_HANG { get; set; }
        public Nullable<decimal> SO_LUONG_MON { get; set; }
        public Nullable<decimal> DON_GIA_MON { get; set; }
        public Nullable<decimal> TIEN_VIET_MON { get; set; }
        public Nullable<decimal> TIEN_GIAM_GIA { get; set; }
        public Nullable<decimal> TIEN_PHAI_TRA { get; set; }
        public Nullable<bool> THEM_BO_SUNG { get; set; }
        public Nullable<bool> COOK_VA_MIXE { get; set; }
        public string NOT_COOK_MIX { get; set; }
    
        public virtual HOA_DON HOA_DON { get; set; }
        public virtual MON_HANG MON_HANG { get; set; }
    }
}
