//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesConnection : DbContext
    {
        public EntitiesConnection()
            : base("name=EntitiesConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAN_MAM> BAN_MAM { get; set; }
        public virtual DbSet<BANG_VON> BANG_VON { get; set; }
        public virtual DbSet<BILL_MEAL> BILL_MEAL { get; set; }
        public virtual DbSet<CHI_NHANH> CHI_NHANH { get; set; }
        public virtual DbSet<CHUNG_TU> CHUNG_TU { get; set; }
        public virtual DbSet<CLIENT_CARDS> CLIENT_CARDS { get; set; }
        public virtual DbSet<COMB_MON> COMB_MON { get; set; }
        public virtual DbSet<COMB_SET> COMB_SET { get; set; }
        public virtual DbSet<DINH_MUC> DINH_MUC { get; set; }
        public virtual DbSet<GIAO_DICH> GIAO_DICH { get; set; }
        public virtual DbSet<HOA_DON> HOA_DON { get; set; }
        public virtual DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public virtual DbSet<KHO_HANG> KHO_HANG { get; set; }
        public virtual DbSet<KHOAN_MUC> KHOAN_MUC { get; set; }
        public virtual DbSet<KHU_VUC> KHU_VUC { get; set; }
        public virtual DbSet<LAM_LENH> LAM_LENH { get; set; }
        public virtual DbSet<LOAI_CARDS> LOAI_CARDS { get; set; }
        public virtual DbSet<LOAI_COUPON> LOAI_COUPON { get; set; }
        public virtual DbSet<LOAI_DICH> LOAI_DICH { get; set; }
        public virtual DbSet<LOAI_KHO> LOAI_KHO { get; set; }
        public virtual DbSet<LOAI_MON> LOAI_MON { get; set; }
        public virtual DbSet<MON_HANG> MON_HANG { get; set; }
        public virtual DbSet<NGUOI_BAN> NGUOI_BAN { get; set; }
        public virtual DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
        public virtual DbSet<NHAP_XUAT> NHAP_XUAT { get; set; }
        public virtual DbSet<NHOM_GIOI> NHOM_GIOI { get; set; }
        public virtual DbSet<NHOM_MON> NHOM_MON { get; set; }
        public virtual DbSet<PHA_NAU> PHA_NAU { get; set; }
        public virtual DbSet<PHONG_BAN> PHONG_BAN { get; set; }
        public virtual DbSet<PUTIN_OUT> PUTIN_OUT { get; set; }
        public virtual DbSet<SODU_HANG> SODU_HANG { get; set; }
        public virtual DbSet<SODU_KHACH> SODU_KHACH { get; set; }
        public virtual DbSet<THEM_TIEN> THEM_TIEN { get; set; }
        public virtual DbSet<TRANG_THAI> TRANG_THAI { get; set; }
        public virtual DbSet<USER_LOGIN> USER_LOGIN { get; set; }
        public virtual DbSet<USER_ZONES> USER_ZONES { get; set; }
        public virtual DbSet<CAU_HINH> CAU_HINH { get; set; }
        public virtual DbSet<CHUC_NANG> CHUC_NANG { get; set; }
        public virtual DbSet<NGHIEP_VU> NGHIEP_VU { get; set; }
        public virtual DbSet<PHAN_NHIEM> PHAN_NHIEM { get; set; }
        public virtual DbSet<BILL_TACH> BILL_TACH { get; set; }
    }
}
