//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAU_HINH
    {
        public short COD_CAU_HINH { get; set; }
        public string TEN_TIEUDE_MOT { get; set; }
        public string TEN_TIEUDE_HAI { get; set; }
        public string TEN_TIEUDE_TAM { get; set; }
        public string TEN_TIEUDE_BON { get; set; }
        public string TEN_PATH_LOGOS { get; set; }
        public string TEN_CHIEF_TOAN { get; set; }
        public string TEN_CHIEF_TONG { get; set; }
        public string CODE_REG_USED { get; set; }
        public Nullable<bool> VIEW_BAR_CODE { get; set; }
        public Nullable<short> TYPE_BAR_CODE { get; set; }
        public string CODE_BAR_CODE { get; set; }
        public Nullable<short> KY_KE_TOAN { get; set; }
        public Nullable<short> NAM_KE_TOAN { get; set; }
        public Nullable<short> KY_HIEN_TAI { get; set; }
        public Nullable<short> NAM_HIEN_TAI { get; set; }
        public Nullable<short> KY_BAO_CAO { get; set; }
        public Nullable<short> DON_GIA_KHO { get; set; }
        public Nullable<short> LAN_SUA_BILL { get; set; }
        public Nullable<System.Guid> KEY_CHI_NHANH { get; set; }
        public string PRINT_PHA_CHE { get; set; }
        public string PRINT_NHA_BEP { get; set; }
        public string PRINT_MAY_BIL { get; set; }
        public Nullable<decimal> DIEM_QUI_UOC { get; set; }
        public Nullable<decimal> DIEM_QUI_DOI { get; set; }
    }
}
