//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUC_NANG
    {
        public string COD_CHUC_NANG { get; set; }
        public string TEN_CHUC_NANG { get; set; }
        public string CHA_CHUC_NANG { get; set; }
    }
}
