//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT_CARDS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT_CARDS()
        {
            this.HOA_DON = new HashSet<HOA_DON>();
        }
    
        public Nullable<System.Guid> KEY_LOAI_CARDS { get; set; }
        public System.Guid KEY_CLIENT_CARDS { get; set; }
        public string COD_CLIENT_CARDS { get; set; }
        public string TEN_CLIENT_CARDS { get; set; }
        public string ADD_CLIENT_CARDS { get; set; }
        public string TEL_CLIENT_CARDS { get; set; }
        public string TAX_CLIENT_CARDS { get; set; }
        public Nullable<decimal> MAR_CLIENT_CARDS { get; set; }
        public Nullable<bool> STA_CLIENT_CARDS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
    }
}
