//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMB_MON
    {
        public Nullable<System.Guid> KEY_COMB_SET { get; set; }
        public System.Guid KEY_COMB_MON { get; set; }
        public Nullable<System.Guid> KEY_MON_HANG { get; set; }
        public Nullable<decimal> SO_LUONG_MON { get; set; }
    
        public virtual COMB_SET COMB_SET { get; set; }
    }
}
