//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMB_SET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMB_SET()
        {
            this.COMB_MON = new HashSet<COMB_MON>();
            this.HOA_DON = new HashSet<HOA_DON>();
        }
    
        public System.Guid KEY_COMB_SET { get; set; }
        public string TEN_COMB_SET { get; set; }
        public Nullable<decimal> GIA_COMB_SET { get; set; }
        public Nullable<short> TYP_COMB_SET { get; set; }
        public Nullable<bool> ACT_COMB_SET { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMB_MON> COMB_MON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
    }
}
