//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DINH_MUC
    {
        public System.Guid KEY_DINH_MUC { get; set; }
        public Nullable<System.Guid> KEY_MON_HANG { get; set; }
        public Nullable<System.Guid> KEY_MAT_HANG { get; set; }
        public Nullable<decimal> SO_LUONG_MUC { get; set; }
    }
}
