//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAO_DICH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAO_DICH()
        {
            this.BANG_VON = new HashSet<BANG_VON>();
            this.BANG_VON1 = new HashSet<BANG_VON>();
            this.SODU_KHACH = new HashSet<SODU_KHACH>();
        }
    
        public System.Guid KEY_GIAO_DICH { get; set; }
        public string COD_GIAO_DICH { get; set; }
        public string TEN_GIAO_DICH { get; set; }
        public string COD_LOAI_DICH { get; set; }
        public string LOAI_CONG_NO { get; set; }
        public Nullable<System.DateTime> DATE_DONG_BO { get; set; }
        public Nullable<short> VERS_DONG_BO { get; set; }
        public Nullable<bool> FLAG_DONG_BO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANG_VON> BANG_VON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANG_VON> BANG_VON1 { get; set; }
        public virtual LOAI_DICH LOAI_DICH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SODU_KHACH> SODU_KHACH { get; set; }
    }
}
