//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA_DON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOA_DON()
        {
            this.BILL_MEAL = new HashSet<BILL_MEAL>();
            this.BILL_TACH = new HashSet<BILL_TACH>();
        }
    
        public Nullable<System.Guid> KEY_BAN_MAM { get; set; }
        public Nullable<System.Guid> KEY_NHAN_VIEN { get; set; }
        public Nullable<System.Guid> KEY_NGUOI_BAN { get; set; }
        public Nullable<System.Guid> KEY_USER_LOGIN { get; set; }
        public Nullable<System.Guid> KEY_CLIENT_CARDS { get; set; }
        public Nullable<decimal> HSO_CLIENT_CARDS { get; set; }
        public Nullable<System.Guid> KEY_LOAI_COUPON { get; set; }
        public Nullable<decimal> VAL_LOAI_COUPON { get; set; }
        public System.Guid KEY_HOA_DON { get; set; }
        public string MA_HOA_DON { get; set; }
        public Nullable<System.DateTime> NGAY_HOA_DON { get; set; }
        public Nullable<System.DateTime> NGAY_GIO_BAN { get; set; }
        public Nullable<decimal> TIEN_THU_VAO { get; set; }
        public Nullable<decimal> TIEN_THOI_LAI { get; set; }
        public Nullable<decimal> TONG_KHUYEN_MAI { get; set; }
        public Nullable<decimal> TONG_PHAI_TRA { get; set; }
        public string GHI_GHI_CHU { get; set; }
        public Nullable<bool> DA_THU_TIEN { get; set; }
        public Nullable<bool> DA_CHE_BIEN { get; set; }
        public Nullable<int> LAN_IN_PHIEU { get; set; }
        public Nullable<System.DateTime> NGAY_GIO_VAO { get; set; }
        public Nullable<System.DateTime> NGAY_GIO_OUT { get; set; }
        public Nullable<decimal> TONG_GIO_USE { get; set; }
        public Nullable<decimal> TONG_TIEN_BO { get; set; }
        public Nullable<System.Guid> KEY_COMB_SET { get; set; }
        public Nullable<decimal> GIA_COMB_SET { get; set; }
        public Nullable<System.Guid> KEY_THEM_TIEN { get; set; }
        public Nullable<decimal> TONG_TANG_GIA { get; set; }
        public Nullable<decimal> DIEM_QUI_UOC { get; set; }
        public Nullable<decimal> DIEM_QUI_DOI { get; set; }
        public Nullable<decimal> TIEN_TRU_DIEM { get; set; }
        public Nullable<decimal> TIEN_TICH_LUY { get; set; }
    
        public virtual BAN_MAM BAN_MAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_MEAL> BILL_MEAL { get; set; }
        public virtual CLIENT_CARDS CLIENT_CARDS { get; set; }
        public virtual COMB_SET COMB_SET { get; set; }
        public virtual NGUOI_BAN NGUOI_BAN { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
        public virtual USER_LOGIN USER_LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_TACH> BILL_TACH { get; set; }
    }
}
