//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACH_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACH_HANG()
        {
            this.NHAP_XUAT = new HashSet<NHAP_XUAT>();
            this.SODU_KHACH = new HashSet<SODU_KHACH>();
        }
    
        public System.Guid KEY_KHACH_HANG { get; set; }
        public string MA_KHACH_HANG { get; set; }
        public string TEN_KHACH_HANG { get; set; }
        public string DIA_CHI_KHACH { get; set; }
        public string SO_DIEN_THOAI { get; set; }
        public string MA_SO_THUE { get; set; }
        public Nullable<decimal> HAN_MUC_NO { get; set; }
        public Nullable<bool> CO_GIAO_DICH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHAP_XUAT> NHAP_XUAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SODU_KHACH> SODU_KHACH { get; set; }
    }
}
