//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHO_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHO_HANG()
        {
            this.PUTIN_OUT = new HashSet<PUTIN_OUT>();
            this.SODU_HANG = new HashSet<SODU_HANG>();
        }
    
        public System.Guid KEY_KHO_HANG { get; set; }
        public string MA_KHO_HANG { get; set; }
        public string TEN_KHO_HANG { get; set; }
        public string DIA_CHI_KHO { get; set; }
        public string SUC_CHUA_KHO { get; set; }
        public string TEN_THU_KHO { get; set; }
        public string MA_LOAI_KHO { get; set; }
    
        public virtual LOAI_KHO LOAI_KHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUTIN_OUT> PUTIN_OUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SODU_HANG> SODU_HANG { get; set; }
    }
}
