//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHU_VUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHU_VUC()
        {
            this.BAN_MAM = new HashSet<BAN_MAM>();
        }
    
        public string MA_KHU_VUC { get; set; }
        public string MA_LOAI_GIA { get; set; }
        public string TEN_KHU_VUC { get; set; }
        public Nullable<int> TT_HIEN_THI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAN_MAM> BAN_MAM { get; set; }
    }
}
