//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAM_LENH
    {
        public Nullable<System.Guid> KEY_CHI_NHANH { get; set; }
        public System.Guid KEY_LAM_LENH { get; set; }
        public Nullable<System.DateTime> NGAY_LAM_LENH { get; set; }
        public string COD_LAM_LENH { get; set; }
        public Nullable<bool> XAC_NHAN_OUT { get; set; }
        public Nullable<System.Guid> KEY_BILL_NHAP { get; set; }
        public Nullable<System.Guid> KEY_BILL_XUAT { get; set; }
    }
}
