//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAI_MON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAI_MON()
        {
            this.NHOM_MON = new HashSet<NHOM_MON>();
        }
    
        public System.Guid KEY_LOAI_MON { get; set; }
        public string MA_LOAI_MON { get; set; }
        public string TEN_LOAI_MON { get; set; }
        public Nullable<System.DateTime> NGAY_DONG_BO { get; set; }
        public Nullable<bool> IS_NEW { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHOM_MON> NHOM_MON { get; set; }
    }
}
