//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAI_COUPON
    {
        public System.Guid KEY_LOAI_COUPON { get; set; }
        public string COD_LOAI_COUPON { get; set; }
        public string TEN_LOAI_COUPON { get; set; }
        public Nullable<System.DateTime> BEG_LOAI_COUPON { get; set; }
        public Nullable<System.DateTime> END_LOAI_COUPON { get; set; }
        public Nullable<int> KIN_LOAI_COUPON { get; set; }
        public Nullable<decimal> VAL_LOAI_COUPON { get; set; }
        public Nullable<int> QTY_LOAI_COUPON { get; set; }
        public Nullable<int> USE_LOAI_COUPON { get; set; }
        public Nullable<int> REM_LOAI_COUPON { get; set; }
    }
}
