//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAI_CARDS
    {
        public System.Guid KEY_LOAI_CARDS { get; set; }
        public string TEN_LOAI_CARDS { get; set; }
        public Nullable<decimal> HSO_LOAI_CARDS { get; set; }
        public Nullable<decimal> MAR_LOAI_CARDS { get; set; }
    }
}
