//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGHIEP_VU
    {
        public Nullable<short> IDX_NGHIEP_VU { get; set; }
        public string MA_NGHIEP_VU { get; set; }
        public string TEN_NGHIEP_VU { get; set; }
        public string MA_LOAI_VIEW { get; set; }
        public string MA_LOAI_XULY { get; set; }
        public Nullable<short> MA_LOAI_SORT { get; set; }
    }
}
