//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOI_BAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUOI_BAN()
        {
            this.HOA_DON = new HashSet<HOA_DON>();
        }
    
        public Nullable<System.Guid> KEY_NHOM_GIOI { get; set; }
        public System.Guid KEY_NGUOI_BAN { get; set; }
        public string MA_NGUOI_BAN { get; set; }
        public string TEN_NGUOI_BAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
        public virtual NHOM_GIOI NHOM_GIOI { get; set; }
    }
}
