//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAP_XUAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHAP_XUAT()
        {
            this.BANG_VON = new HashSet<BANG_VON>();
            this.PUTIN_OUT = new HashSet<PUTIN_OUT>();
        }
    
        public Nullable<System.Guid> KEY_CHI_NHANH { get; set; }
        public Nullable<System.Guid> KEY_CHUNG_TU { get; set; }
        public Nullable<System.Guid> KEY_NGUOI_DUNG { get; set; }
        public Nullable<System.Guid> KEY_KHACH_HANG { get; set; }
        public System.Guid KEY_NHAP_XUAT { get; set; }
        public string KY_HIEU_PHIEU { get; set; }
        public string SO_NHAP_XUAT { get; set; }
        public string SO_HOA_DON { get; set; }
        public string HIEU_HOA_DON { get; set; }
        public Nullable<System.DateTime> NGAY_NHAP_XUAT { get; set; }
        public string TEN_KHACH_HANG { get; set; }
        public string DIA_CHI_KHACH { get; set; }
        public string SO_TEL_KHACH { get; set; }
        public string LYDO_NHAP_XUAT { get; set; }
        public Nullable<bool> KHAI_THUE_VAT { get; set; }
        public Nullable<bool> HOA_DON_KYGUI { get; set; }
        public Nullable<short> COD_TRANG_THAI { get; set; }
        public string GHI_NHAP_XUAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANG_VON> BANG_VON { get; set; }
        public virtual CHI_NHANH CHI_NHANH { get; set; }
        public virtual CHUNG_TU CHUNG_TU { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual USER_LOGIN USER_LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUTIN_OUT> PUTIN_OUT { get; set; }
    }
}
