//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHOM_GIOI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHOM_GIOI()
        {
            this.NGUOI_BAN = new HashSet<NGUOI_BAN>();
        }
    
        public System.Guid KEY_NHOM_GIOI { get; set; }
        public string MA_NHOM_GIOI { get; set; }
        public string TEN_NHOM_GIOI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGUOI_BAN> NGUOI_BAN { get; set; }
    }
}
