//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SODU_KHACH
    {
        public System.Guid KEY_SODU_KHACH { get; set; }
        public Nullable<System.Guid> KEY_KHACH_HANG { get; set; }
        public Nullable<System.Guid> KEY_GIAO_DICH { get; set; }
        public Nullable<short> KY_KE_TOAN { get; set; }
        public Nullable<short> NAM_KE_TOAN { get; set; }
        public Nullable<decimal> TIEN_MUA_BAN { get; set; }
        public Nullable<decimal> TIEN_NODA_TRA { get; set; }
    
        public virtual GIAO_DICH GIAO_DICH { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
