//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SODU_HANG
    {
        public System.Guid KEY_SODU_HANG { get; set; }
        public Nullable<System.Guid> KEY_KHO_HANG { get; set; }
        public Nullable<System.Guid> KEY_MAT_HANG { get; set; }
        public Nullable<short> KY_KE_TOAN { get; set; }
        public Nullable<short> NAM_KE_TOAN { get; set; }
        public Nullable<decimal> DON_GIA_HANG { get; set; }
        public Nullable<decimal> SO_LUONG_HANG { get; set; }
        public Nullable<decimal> TIEN_VIET_NAM { get; set; }
    
        public virtual KHO_HANG KHO_HANG { get; set; }
    }
}
