//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THEM_TIEN
    {
        public System.Guid KEY_THEM_TIEN { get; set; }
        public string COD_THEM_TIEN { get; set; }
        public string TEN_THEM_TIEN { get; set; }
        public Nullable<short> HSO_THEM_TIEN { get; set; }
    }
}
