//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_LOGIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_LOGIN()
        {
            this.HOA_DON = new HashSet<HOA_DON>();
            this.NHAP_XUAT = new HashSet<NHAP_XUAT>();
        }
    
        public System.Guid KEY_USER_LOGIN { get; set; }
        public string COD_USER_LOGIN { get; set; }
        public string TEN_USER_LOGIN { get; set; }
        public string PAS_USER_LOGIN { get; set; }
        public string POS_USER_LOGIN { get; set; }
        public Nullable<bool> ACT_USER_LOGIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHAP_XUAT> NHAP_XUAT { get; set; }
    }
}
